### ISSUE TITLE
Add syntax description for credential mapping

### ISSUE THREAD

**Issue by maxveit** [ibm-cloud-docs/security-compliance#1]
In this section: https://cloud.ibm.com/docs/security-compliance?topic=security-compliance-credentials#map-credentials there is no notion of which syntax can be used in the Criteria field.

**Comment by smguilia** [comment]
Hi Max,

Thanks for opening this! I've opened an issue internally so that we can get it sprinted. I'll let you know when the updates are available. Please don't hesitate to reach out with more feedback.

- Shawna
