### ISSUE TITLE
No Service by name 'Security and Compliance Integrations'

### ISSUE THREAD

**Issue by krishna-rajeesh** [ibm-cloud-docs/security-compliance#1]
Hi Team,

Please update the doc. There is No Service by name 'Security and Compliance Integrations'.  Thanks.

Refer doc: https://cloud.ibm.com/docs/security-compliance?topic=security-compliance-ibm-credential#ibm-service-id-policies

5. Assign access to the Security and Compliance Center and 'Security and Compliance Integrations'.

From the table, select the Security and Compliance Center and click Next.
Leave All resources and click Next.
Select Manager and Administrator. Then, click Review to validate your choices.
Click Add.
Repeat all of step 5, but select **Security and Compliance Integrations** instead of Security and Compliance Center.

**Comment by smguilia** [comment]
Hi @krishna-rajeesh,

Thank you for taking the time to open this issue. I apologize for the delayed response - I addressed your feedback some time ago and forgot to come back and update this issue. The references to that service name should be removed. Please let me know if you have any additional feedback in the future.

-Shawna
