### ISSUE TITLE
SCC terraform docs doesn't actually give any information on the IBM terraform provider resources 

### ISSUE THREAD

**Issue by ocofaigh** [ibm-cloud-docs/security-compliance#10]
Doc: https://cloud.ibm.com/docs/security-compliance?topic=security-compliance-terraform-setup

In step 2 of above doc you instruct users to use the UI, API, or CLI to provision an SCC instance, yet the whole purpose of the doc is to inform users how they can use terraform to provision the infrastructure. Why not point them to the [ibm_resource_instance](https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/resource_instance) doc, and leave a code snippet with an example on how to provision an instance. For example:

```
resource "ibm_resource_instance" "scc_instance" {
  name              = "test"
  service           = "compliance"
  plan              = "security-compliance-center-standard-plan" # also support security-compliance-center-trial-plan
  location          = "us-south"
  resource_group_id = data.ibm_resource_group.group.id
  tags              = ["tag1", "tag2"]
}
```

There is also no mention in the docs on the actual IBM provider resources that can be used to provision SCC resources. In step 3 you point to the [hashicorp CLI docs](https://developer.hashicorp.com/terraform/cli/run) yet you mention `main.tf` so you should really be pointing to the IBM terraform provider docs, specifically the SCC related resources such as:

- [ibm_scc_control_library](https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/scc_control_library)
- [ibm_scc_profile](https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/scc_profile)
- [ibm_scc_profile_attachment](https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/scc_profile_attachment)
- [ibm_scc_provider_type_instance](https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/scc_provider_type_instance)
- [ibm_scc_rule](https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/scc_rule)

**Comment by smguilia** [comment]
Thank you for opening an issue @ocofaigh. I'm closing this as I have opened a new issue internally so that your suggestion can be prioritized.
