### ISSUE TITLE
Rephrase the definition of Profiles

### ISSUE THREAD

**Issue by lionelmace** [ibm-cloud-docs/security-compliance#11]
I assume the following phrase
```
A profile is a collection of related goals, or security checks, are used to validate that your the compliance of your resources to internal and external regulations.
```
should be replaced by
```
A profile is a collection of related goals, or security checks, are used to validate that your resources are compliant with internal and external regulations.
```
https://cloud.ibm.com/docs/security-compliance?topic=security-compliance-profiles

**Comment by smguilia** [comment]
Hi @lionelmace,

It should. Thank you for opening an issue! I've updated the docs internally and it will be updated as part of the next production push. 

If you come across other defects, please don't hesitate to open another issue in the future.

 -- Shawna
