### ISSUE TITLE
Add ROKS to list

### ISSUE THREAD

**Issue by vwilburn** [ibm-cloud-docs/security-compliance#12]
Hi, would you add "Red Hat OpenShift on IBM Cloud" to this list: https://cloud.ibm.com/docs/security-compliance?topic=security-compliance-faqs&interface=ui#resource-scan 
**Which IBM Cloud services can I scan?**

You'll also need to update the item called "Kubernetes Service" to "IBM Cloud Kubernetes Service" to be clear which services are scannable.

Thanks!

**Comment by smguilia** [comment]
Hi,

Added OpenShift as a product. Thanks for pointing that out! I did not update Kubernetes service as the list is specific to IBM Cloud services and we are using the approved shortname conrefs for each service.
