### ISSUE TITLE
The format of section 6 seems wring

### ISSUE THREAD

**Issue by LarsIpsen** [ibm-cloud-docs/security-compliance#15]
Section 6 seems to be mis-formated:
`| Tier mapping | Definition | Commonly used terms | | --------- | ----------- | | Web tier | The web tier of your deployment architecture is generally written in HTML, CSS, or JavaScript and is presented to a user through a web browser or application. | Front end, web, browser, client, or presentation. | | App tier | The app tier of your deployment architecture is written in a programming language, such as Java or Go, and contains the business logic that supports your application's core function. | Logic, core, application, backend, or APIs. | | DB tier | The database tier of your deployment architecture consists of a database and the system that is used to manage it, such as MySQL or MongoDB. | Server, storage, or database. | | Data tier | The data tier of your deployment architecture consists of application storage that might not be specific to a database or communication port. | Storage or log files. |`

**Comment by smguilia** [comment]
Fixed, thank you!
