### ISSUE TITLE
Please update pages to exchange 'Gen 1 classic infrastructure' with 'Classic infrastructure' 

### ISSUE THREAD

**Issue by guategringo** [ibm-cloud-docs/security-compliance#18]
This is a request to change the text references to Classic infrastructure in SCC Doc pages.  Specifically, please change 'Gen 1 classic infrastructure' with 'Classic infrastructure' in the following pages:

- https://cloud.ibm.com/docs/security-compliance?topic=security-compliance-known-issues-limits
- https://cloud.ibm.com/docs/security-compliance?topic=security-compliance-schedule-scan
- https://cloud.ibm.com/docs/security-compliance?topic=security-compliance-insights-rules
- https://cloud.ibm.com/docs/security-advisor?topic=security-advisor-insights-rules

**Comment by smguilia** [comment]
@guategringo Thanks for opening this issue. I've made the updates. I reached out on Slack to confirm capitalization. Please don't hesitate to let me know if you have other feedback on the documentation.

- Shawna

**Comment by guategringo** [comment]
awesome thank you @smguilia !
