### ISSUE TITLE
Command for pasting into a windows server does not work by clicking the Copy symbol

### ISSUE THREAD

**Issue by DougAtIBM** [ibm-cloud-docs/security-compliance#19]
on this page, https://cloud.ibm.com/docs/security-compliance?topic=security-compliance-schedule-scan#windows-prereq the second step does not copy over correctly to a windows powershell. it needs to be separated into 3 commands like this:

$myhost=(Get-WmiObject win32_computersystem).DNSHostName+"."+ (Get-WmiObject win32_computersystem).Domain

$Cert = New-SelfSignedCertificate -CertstoreLocation Cert:\LocalMachine\My -DnsName $myhost

New-Item -Path WSMan:\LocalHost\Listener -Transport HTTPS -Address * -CertificateThumbPrint $Cert.Thumbprint -Force

**Comment by smguilia** [comment]
Hi @DougAtIBM,

Thank you for taking the time to open this issue. I apologize for the delayed response. The issue was fixed this morning. Please don't hesitate to open additional issues in the future if you come across them or have ideas for how the docs can be approved in the future.

Shawna
