### ISSUE TITLE
Add IPs / FQDNs and Ports of SCC endpoints for the collector

### ISSUE THREAD

**Issue by maxveit** [ibm-cloud-docs/security-compliance#2]
In this section: https://cloud.ibm.com/docs/security-compliance?topic=security-compliance-collector#install-collector it would be great to have a list of private and public endpoints and ports, that would be needed to allowed in a firewall if one is sitting in a "locked-down" environment.

**Comment by smguilia** [comment]
Hi Max,

Thanks for opening this! I've opened an issue internally so that we can get it sprinted. I'll let you know when the updates are available. Please don't hesitate to reach out with more feedback.

Shawna
