### ISSUE TITLE
Doubly defined "parameter"

### ISSUE THREAD

**Issue by apham0072** [ibm-cloud-docs/security-compliance#2]
Not sure if it was intentional; however, "Parameter" is defined twice on this page: https://cloud.ibm.com/docs/security-compliance?topic=security-compliance-key-concepts

Though the definitions are pretty much equivalent, perhaps combine them to avoid question.

**Comment by h-romeus** [comment]
@apham0072  Thank you for opening this issue! I've addressed your feedback and reviewed with the development team. Please don't hesitate to open additional feedback in the future.

-Hadassa
