### ISSUE TITLE
SCC "Create a scope" instructions needs an update

### ISSUE THREAD

**Issue by ChuckCox** [ibm-cloud-docs/security-compliance#20]
In the this tutorial (https://cloud.ibm.com/docs/security-compliance?topic=security-compliance-scopes), under the "Creating a scope" section, step 6 mentions "Select the Credentials that match the collector that you selected in the previous step." However, the collector is selected in the next step (step 8 actually).  

One gotcha though is if a person does not have a collector already created, the creation of the scope comes to a halt (see below screenshot), with no way to create a collector in the process.  

![Screen Shot 2022-01-04 at 4 40 21 PM](https://user-images.githubusercontent.com/19801489/148134643-c0968d20-3a9c-4235-a64a-ed6e0b338a8c.png)

So, there probably needs to be a "NOTE" at the beginning of these instructions to warm people to make sure they have a collector already created prior to starting the steps under the "Creating a scope" section.

**Comment by smguilia** [comment]
Hi @ChuckCox,

Thank you for taking the time to open this issue. I apologize for the delayed response. The issue was fixed this morning. Please don't hesitate to open additional issues in the future if you come across them or have ideas for how the docs can be approved in the future.

Shawna
