### ISSUE TITLE
Link to terraform registry for SCC broken 

### ISSUE THREAD

**Issue by rjminsha** [ibm-cloud-docs/security-compliance#21]
[Security and Compliance Center Terraform registry](https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/scc) link is no longer valid.  

Should likely link to main page for IBM provider https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs

**Comment by smguilia** [comment]
Hi @rjminsha,

Thank you for taking the time to open this issue. I apologize for the delayed response. The issue was fixed this morning. Please don't hesitate to open additional issues in the future if you come across them or have ideas for how the docs can be approved in the future.

Shawna
