### ISSUE TITLE
404s for links to collector

### ISSUE THREAD

**Issue by SirSpidey** [ibm-cloud-docs/security-compliance#23]
In `getting-started.md`, the links in this sentence result in 404s:

> To start monitoring compliance, choose whether to [create and install a collector](https://cloud.ibm.com/docs/security-compliance?topic=security-compliance-ibm-customer-collector) or [provision a managed one](https://cloud.ibm.com/docs/security-compliance?topic=security-compliance-monitor-ibm-collector).

**Comment by smguilia** [comment]
Thanks Allen! - Fixed.
