### ISSUE TITLE
Improper TF datasource syntax

### ISSUE THREAD

**Issue by evanrappe** [ibm-cloud-docs/security-compliance#24]
In ["Setting up Terraform for Security and Compliance Center](https://cloud.ibm.com/docs/security-compliance?topic=security-compliance-terraform-setup&interface=ui) the example datasource declaration states a `scope_id` value. This is not allowed in the current provider, it errors out.

```hcl
data "ibm_scc_posture_scopes" "list_scopes" {
  scope_id = "1"
}
```

It must be called with no parameters.
```hcl
data "ibm_scc_posture_scopes" "list_scopes" {
}
```

**Comment by smguilia** [comment]
Hi @evanrappe,

Thanks for taking the time to open this issue. I've made the update that you suggested. Please don't hesitate to open additional issues or ideas to help improve our content as you continue to work with the service. 

Shawna
