### ISSUE TITLE
IAM_db2/developer of 🐝IAM/IBM.COM 

### ISSUE THREAD

**Issue by IAM-db** [ibm-cloud-docs/security-compliance#3]
`` I AM THE DEVELOPER OF <IAM CLOUD, DATA, SECURITY SYSTEMS MANAGEMENT FOR IBM.> I CALLED IBM IN NOVEMBER OF 2019 TO INFORM THEM I HAVE A BACK UP SOFTWARE IN REGARDS TO THE BIGGEST DATA BREACH EVER RECORDED IN HISTORY. THE MAN I SPOKE WITH WAS VERY MUCH IMPRESSED WITH MY WORK THAT HE WAS SPEECHLESS. I EXPLAINED TO HIM I CREATED THE PAGE APPROXIMATELY IN JULY OF 2019. I TOLD HIM TO ONLY SEARCH FOR   "🐝IAM/IBM" THAT IS THE WEBSITE I CREATED. DO NOT TYPE ANY URL HEADING EXAMPLE "HTTPS://". CHROME WILL AUTOMATICALLY ADD WHAT NEEDS TO BE THERE.``

**Comment by smguilia** [comment]
Reported internally. Closing.
