### ISSUE TITLE
Assigning access to Security and Compliance Center

### ISSUE THREAD

**Issue by sarithaarun** [ibm-cloud-docs/security-compliance#4]
In the doc : https://cloud.ibm.com/docs/security-compliance?topic=security-compliance-assign-roles

There is a problem with the access permissions. When assigning access, first we need to choose the service, then we need to choose "How do you want to scope the access?", then the level of access needs to be defined. That level of access is at 3 levels : 
service access and platform access. The current screenshot on the document does not show any of these information hence it is difficult to know what options to choose in order to assign access.

**Comment by smguilia** [comment]
I've opened an issue to track this feedback internally.
