### ISSUE TITLE
Hyperlink missing from doc

### ISSUE THREAD

**Issue by ocofaigh** [ibm-cloud-docs/security-compliance#6]
Page: https://cloud.ibm.com/docs/security-compliance?topic=security-compliance-storage

Issue: I imagine the text "See Cloud Object Storage pricing for more information." should be hyperlinked to some other site that shows COS pricing breakdown?

**Comment by smguilia** [comment]
Added. This change will be visible in production next week as part of a larger push. 

I apologize for the delay in our response. Thank you for taking the time to open the feedback. Please continue to do so if you see issues in the documentation.
