### ISSUE TITLE
Incorrect documentation

### ISSUE THREAD

**Issue by andrewj2000** [ibm-cloud-docs/security-compliance#8]
I do not believe this documentation is correct:
https://cloud.ibm.com/docs/security-compliance?topic=security-compliance-scan-resources&interface=ui

No where on the Profile page is there an option to scan a profile.

I believe step 2 should refer users to the "Attachments" page and not the "Profiles".

Also, this is first time I've seen the term "overflow" menu. Perhaps adding a icon of the vertical ellipses would be helpful.

**Comment by andrewj2000** [comment]
I would also suggest adding this line to this page which only appears in the Troubleshooting section of the document: "When an scan is run, the results for your account are cached for an hour." This is actually an important piece of information that shouldn't be buried in the troubleshooting guide!

**Comment by h-romeus** [comment]
Hello @andrewj2000, thank you very much for your feedback. We've addressed the issue and you can now review it. In the future, please don't hesitate to open more issues, we appreciate it. -Hadassa
